services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./app:/code/app

  db:
    image: postgres:16
    env_file:
      - .env
    environment:
      - POSTGRES_USER=iac_user
      - POSTGRES_PASSWORD=iac_pass
      - POSTGRES_DB=iac_project
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: