services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://iac_user:iac_pass@db:5432/iac_project
      - ANSIBLE_CONFIG=/code/ansible/ansible.cfg
    volumes:
      - ./app:/code/app
      - ./ansible:/code/ansible
      - ./instances:/code/instances
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=iac_user
      - POSTGRES_PASSWORD=iac_pass
      - POSTGRES_DB=iac_project
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
