[workers]
worker1 ansible_host=192.168.56.11 ansible_ssh_private_key_file=.vagrant/machines/worker1/libvirt/private_key
worker2 ansible_host=192.168.56.12 ansible_ssh_private_key_file=.vagrant/machines/worker2/libvirt/private_key
worker3 ansible_host=192.168.56.13 ansible_ssh_private_key_file=.vagrant/machines/worker3/libvirt/private_key

[workers:vars]
ansible_user=vagrant
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes'